version: '3.7'

services:
  laravel:
    container_name: 'laravel'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Docker/Dockerfile
    networks:
      - laravel-network
    depends_on:
      - node
    volumes:
      - './:/var/www/html'

  nginx:
    container_name: 'nginx'
    image: nginx:alpine
    volumes:
      - './:/var/www/html'
      - './Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "80:80"
    depends_on:
      - laravel
    networks:
      - laravel-network

  node:
    image: node:lts-alpine3.19
    container_name: 'node'
    working_dir: /app
    volumes:
      - './:/app'
    command: > 
      sh -c "npm install && npm run dev"
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - laravel-network

  mailpit:
    image: axllent/mailpit
    container_name: 'mailpit'
    restart: always
    volumes:
      - ./data/mailpit:/data
    ports:
      - "${MAIL_PORT}:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge